### ISSUE TITLE
implicit expansion on matlab script

### ISSUE THREAD

**Issue by huankiki** [d-kitamura/AuxIVA-ISS#2]
hi, kitamura,

Thanks for your sharing on BSS scripts which help me a lot on understanding BSS algorithms.
Here is a question.
There are many implicit expansions at matlab script, where I counter error when running it at Matlab R2013a.
for example, in AuxIVAISS.m
`YY = Y .* conj(Y(n,:,:)); % N x J x I, using implicit expansion (NxJxI .* 1xJxI)`

1. do you use other version of Matlab, so  you can run the scripts without error?
2. I'm not sure what this multiplication with expansion really mean?

**Comment by d-kitamura** [comment]
I'm using the newest version on MATLAB, namely, R2021a.
Implicit expansion was implemented in R2016b or later.
https://nhigham.com/2016/09/20/implicit-expansion-matlab-r2016b/

So, the codes do not run on R2013a.
I recommend to update your MATLAB, or you can modify the codes not to use implicit expansion by rewriting them using repmat function.
For example, 
`YY = Y .* conj(Y(n,:,:)); % N x J x I, using implicit expansion (NxJxI .* 1xJxI)`
should be
`YY = Y .* repmat(conj(Y(n,:,:)), [N, 1, 1]); % N x J x I, using implicit expansion (NxJxI .* 1xJxI)`, 
where repmat is used to copy the input variable (conj(Y(n,:,:)) in the above case) so that the size of matrix becomes equal.
Please see https://mathworks.com/help/matlab/ref/repmat.html
